### ISSUE TITLE
oooops!

### ISSUE THREAD

**Issue by yuanminglove** [Community-BL-IOT/pio-bl602-boufallo-arduino-test#1]
I don't how to run the project!!!
Error: Unknown board ID 'pinecone'

**Comment by maxgerhardt** [comment]
I've updated the `platform= ..` path in the `platformio.ini` in 2ee8184a353ff499c89a705de5e39804152efc1f, try redownloading and rebuilding the project.

CI says the build goes through okay: https://github.com/Community-BL-IOT/pio-bl602-boufallo-arduino-test/actions/runs/3549321525/jobs/5961567992

The `pinecone.json` should be in `<home directory>/.platformio/platforms/sifive[@...]/boards/pinecone.json`.

**Comment by maxgerhardt** [comment]
Please reopen if you still need help.
